apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app # Match the selector of the service. Deploy labels = Service selector
    spec:
      containers:
      - name: python-app
        image: krutika09/k8-svc-python-app:v1
        ports:
        - containerPort: 8000
