apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  type: NodePort
  selector:
    app: python-app #Match the selector of the service. Deploy labels=Service selector
  ports:
    - port: 80
      targetPort: 8000 #Target port is your application is running on
      nodePort: 30007 #You can give by your choice
